[package]
name = "fusion_bridge"
version = "1.0.0"
upgrade_policy = "compatible"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }

[addresses]
fusion_bridge = "0xbe96f912fdfb842460fb5985654cc48c403f16d9ae88d33c20b533093881f0e5"
